version: '3.8'

services:
  kong-database:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    networks:
      - kong-network
    ports:
      - "5432:5432"
    volumes:
      - kong-db-data:/var/lib/postgresql/data

  kong-migrations:
    image: kong:latest
    command: kong migrations bootstrap
    networks:
      - kong-network
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    depends_on:
      - kong-database

  kong:
    image: kong:latest
    depends_on:
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    ports:
      - "8000:8000"   # Kong Gateway
      - "8443:8443"   # Kong Gateway SSL
      - "8001:8001"   # Kong Admin API
      - "8444:8444"   # Kong Admin API SSL
    networks:
      - kong-network

  konga:
    image: pantsel/konga
    ports:
      - "1337:1337"   # Konga web interface
    networks:
      - kong-network
    environment:
      NODE_ENV: production
    depends_on:
      - kong
    volumes:
      - konga-data:/app/konga-data

networks:
  kong-network:
    driver: bridge

volumes:
  kong-db-data:
  konga-data:
